name: generic push feature

on:
  push:
    branches:
      - "*"         # matches every branch
      - "*/*"       # matches every branch containing a single '/'
      - "!master"
      - "!develop"

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: node:12.16.2
    steps:
      - uses: actions/checkout@v2
      #Decryption
      - name: Decrypt the GPG encrypted config files
        run: gpg --quiet --batch --yes --passphrase="${{ secrets.GPG_SECRET }}" --output ./src/config.json --decrypt ./src/config.production.json.gpg

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present
        env:
          CI: true

      - name: Test
        run: npm test
        env:
          CI: true