name: develop push

on:
  push:
    branches: [develop]

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USER }}/${{ secrets.REPOSITORY_NAME }}:${{ github.sha }}
  DOCKER_IMAGE_LATEST: ${{ secrets.DOCKER_USER }}/${{ secrets.REPOSITORY_NAME }}:develop

jobs:
  build:

    runs-on: ubuntu-18.04

    # Run the steps in a Docker container on the virtual machine
    container:
      image: node:12.16.2

    steps:
      # Checkout Git repository
      - uses: actions/checkout@v2

        #Decryption
      - name: Decrypt the GPG encrypted config files
        run: gpg --quiet --batch --yes --passphrase="${{ secrets.GPG_SECRET }}" --output ./src/config.json --decrypt ./src/config.production.json.gpg
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present
        env:
          CI: false

      - name: Test
        run: npm test
        env:
          CI: false

      - name: Upload release artifact
        uses: actions/upload-artifact@v1
        with:
          name: release-artifact
          path: ./build

      - name: Upload Dockerfile artifact
        uses: actions/upload-artifact@v1
        with:
          name: dockerfile-artifact
          path: ./Dockerfile

      - name: Upload Kubernetes artifact
        uses: actions/upload-artifact@v1
        with:
          name: kubernetes-artifact
          path: ./kube

  delivery:
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v1
        with:
          name: release-artifact
          path: ./build
      - name: Download Dockerfile artifact
        uses: actions/download-artifact@v1
        with:
          name: dockerfile-artifact
          path: .

      - name: Deliver Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
          docker build -t $DOCKER_IMAGE -t $DOCKER_IMAGE_LATEST .
          docker push $DOCKER_IMAGE
          docker push $DOCKER_IMAGE_LATEST